language: node_js
sudo: false
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
deploy:
  provider: npm
  email: tlaziuk@gmail.com
  api_key:
    secure: JMrf87Fc+T7Doq/Z1JzoioBhUT+66ar3ISuSuHWQYsOq2bP6oahXdR3z5ca4VrNGVpPZrsLvL8i0b/VuYY1YYhAupOgiayl3lZSBga1hiF7s89Qz+mVOkXJd81VYads0F+hXOpO2lP8I/n+NOB2bDLsdhNujrh1k1Y+XJ5KVLAnh/gZhrC+lXRgMapvFOlwYCrBm7QWso6UnVGQF5XW9/J0pwswAhoMBnqqhFiPS4gwU5QC+5Ttu35pvd3kl89/0emfcyudUu+6LecZybugOnNHo1QTYpaOSlLPBVTXFeVELWFcemAZmDOgUhGmbutoaM1bK3VJWhk7HRug39y1r/lUZvfSeP8yS2zVPwTEh5bhqjaNEu0oHLvzzL2R7Mxz0OXVvRHg+BcemTVH34hRW6pqY/elYRM60LRWMzxgKOVo7yxI8/dPNdayPdZBTBwLfBb4osQe3C7zBDlkTQ1clr9TqaM67OzpZ83bltTC5lULYuz4qvkSdjKwF5bA5jGFsBiU3dyTXF+MjTZjeLLzXEL8emuoo7aOa5oN5WjXB1nmn8ywM1ozjsh9mZYp+elZ3bb2BeFPu/uRBkg8HlcqqhxTm92eHxMg8xvK9iUnJVOpONvNKaumZILOnHBNWvOSyrF5nacXbxv7XikZSpGwJbmmymLeB6wV1E4uAPhUylxE=
    on:
      tags: true
      repo: tlaziuk/mithril-render
